spring.application.name=gemini_chatbot
#gemini.api.url=${GEMINI_API_URL}
#gemini.api.key=${GEMINI_API_KEY}
spring.main.banner-mode=off
logging.level.root=ERROR
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyC3LaH5aX2rlTJJZFuLj-3L9Cyetj3P2So
gemini.api.key=AIzaSyC3LaH5aX2rlTJJZFuLj-3L9Cyetj3P2So